Extend release script to support new, semver-tagged releases

diff --git a/release b/release
--- a/release
+++ b/release
@@ -1,4 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+PACKAGE_NAME='beaver'
+PUBLIC="true"
 
 # Colors
 COLOR_OFF="\033[0m"   # unsets color to term fg color
@@ -8,12 +11,17 @@ YELLOW="\033[0;33m"   # yellow
 MAGENTA="\033[0;35m"  # magenta
 CYAN="\033[0;36m"     # cyan
 
+if [[ "$@" != "major" ]] && [[ "$@" != "minor" ]] && [[ "$@" != "patch" ]]; then
+    echo -e "${RED}WARNING: Invalid release type, must specify 'major', 'minor', or 'patch'${COLOR_OFF}\n"
+    exit 1
+fi
+
 echo -e "\n${GREEN}STARTING RELEASE PROCESS${COLOR_OFF}\n"
 
 git status | grep "working directory clean" &> /dev/null
 if [ ! $? -eq 0 ]; then # working directory is NOT clean
-  echo -e "${RED}WARNING: You have uncomitted changes, you may have forgotten something${COLOR_OFF}\n"
-  exit
+    echo -e "${RED}WARNING: You have uncomitted changes, you may have forgotten something${COLOR_OFF}\n"
+    exit 1
 fi
 
 echo -e "${YELLOW}--->${COLOR_OFF} Updating local copy"
@@ -21,8 +29,23 @@ git pull -q origin master
 
 echo -e "${YELLOW}--->${COLOR_OFF} Retrieving release versions"
 
-current_version=`cat beaver/__init__.py |grep '__version__ ='|sed 's/[^0-9]//g'`
-next_version=$(($current_version + 1));
+current_version=`cat ${PACKAGE_NAME}/__init__.py |grep '__version__ ='|sed 's/[^0-9.]//g'`
+major=`echo $current_version | awk '{split($0,a,"."); print a[1]}'`
+minor=`echo $current_version | awk '{split($0,a,"."); print a[2]}'`
+patch=`echo $current_version | awk '{split($0,a,"."); print a[3]}'`
+
+if [[ "$@" == "major" ]]; then
+    major=$(($major + 1));
+    minor="0"
+    patch="0"
+elif [[ "$@" == "minor" ]]; then
+    minor=$(($minor + 1));
+    patch="0"
+elif [[ "$@" == "patch" ]]; then
+    patch=$(($patch + 1));
+fi
+
+next_version="${major}.${minor}.${patch}"
 
 echo -e  "${YELLOW}   >${COLOR_OFF} ${MAGENTA}${current_version}${COLOR_OFF} -> ${MAGENTA}${next_version}${COLOR_OFF}"
 
@@ -30,29 +53,33 @@ echo -e "${YELLOW}--->${COLOR_OFF} Creating necessary temp file"
 tempfoo=`basename $0`
 TMPFILE=`mktemp /tmp/${tempfoo}.XXXXXX` || {
     echo -e "${RED}WARNING: Cannot create temp file using mktemp in /tmp dir ${COLOR_OFF}\n"
-	exit 1
+    exit 1
 }
 
 find_this="__version__ = '$current_version'"
 replace_with="__version__ = '$next_version'"
 
-echo -e "${YELLOW}--->${COLOR_OFF} Updating beaver/__init__.py"
-sed "s/$find_this/$replace_with/" beaver/__init__.py > $TMPFILE && mv $TMPFILE beaver/__init__.py
-
-find_this="pip install beaver==$current_version"
-replace_with="pip install beaver==$next_version"
+echo -e "${YELLOW}--->${COLOR_OFF} Updating ${PACKAGE_NAME}/__init__.py"
+sed "s/$find_this/$replace_with/" ${PACKAGE_NAME}/__init__.py > $TMPFILE && mv $TMPFILE ${PACKAGE_NAME}/__init__.py
 
 echo -e "${YELLOW}--->${COLOR_OFF} Updating README.rst"
+find_this="${PACKAGE_NAME}.git@$current_version"
+replace_with="${PACKAGE_NAME}.git@$next_version"
+sed "s/$find_this/$replace_with/" README.rst > $TMPFILE && mv $TMPFILE README.rst
+find_this="${PACKAGE_NAME}==$current_version"
+replace_with="${PACKAGE_NAME}==$next_version"
 sed "s/$find_this/$replace_with/" README.rst > $TMPFILE && mv $TMPFILE README.rst
 
-echo -e "${YELLOW}--->${COLOR_OFF} Updating docs"
-find_this="version = '${current_version}'"
-replace_with="version = '${next_version}'"
-sed "s/$find_this/$replace_with/" docs/conf.py > $TMPFILE && mv $TMPFILE docs/conf.py
+if [ -f docs/conf.py ]; then
+    echo -e "${YELLOW}--->${COLOR_OFF} Updating docs"
+    find_this="version = '${current_version}'"
+    replace_with="version = '${next_version}'"
+    sed "s/$find_this/$replace_with/" docs/conf.py > $TMPFILE && mv $TMPFILE docs/conf.py
 
-find_this="version = '${current_version}'"
-replace_with="release = '${next_version}'"
-sed "s/$find_this/$replace_with/" docs/conf.py > $TMPFILE && mv $TMPFILE docs/conf.py
+    find_this="release = '${current_version}'"
+    replace_with="release = '${next_version}'"
+    sed "s/$find_this/$replace_with/" docs/conf.py > $TMPFILE && mv $TMPFILE docs/conf.py
+fi
 
 echo -e "${YELLOW}--->${COLOR_OFF} Updating CHANGES.rst for new release"
 version_header="$next_version ($(date +%F))"
@@ -60,7 +87,8 @@ dashes=`yes '-'|head -n ${#version_header}|tr -d '\n'`
 gitchangelog |sed "4s/.*/$version_header/"|sed "5s/.*/$dashes/" > $TMPFILE && mv $TMPFILE CHANGES.rst
 
 echo -e "${YELLOW}--->${COLOR_OFF} Adding changed files to git"
-git add CHANGES.rst README.rst beaver/__init__.py docs/conf.py
+git add CHANGES.rst README.rst ${PACKAGE_NAME}/__init__.py
+if [ -f docs/conf.py ]; then git add docs/conf.py; fi
 
 echo -e "${YELLOW}--->${COLOR_OFF} Creating release"
 git commit -q -m "Release version $next_version"
@@ -71,9 +99,11 @@ git tag -a $next_version -m "Release version $next_version"
 echo -e "${YELLOW}--->${COLOR_OFF} Pushing release and tags to github"
 git push -q origin master && git push -q --tags
 
-echo -e "${YELLOW}--->${COLOR_OFF} Creating python release"
-cp README.rst README
-python setup.py sdist upload > /dev/null
-rm README
+if [[ "$PUBLIC" == "true" ]]; then
+    echo -e "${YELLOW}--->${COLOR_OFF} Creating python release"
+    cp README.rst README
+    python setup.py sdist upload > /dev/null
+    rm README
+fi
 
 echo -e "\n${CYAN}RELEASED VERSION ${next_version}!${COLOR_OFF}\n"
